l1= float(input("Entre com valor do lado 1: "))
l2= float(input("Entre com valor do lado 2: "))
l3= float(input("Entre com valor do lado 3: "))
l4= float(input("Entre com valor do lado 4: "))
area = (l2 * l3 )
perimetro = (l1 + l2 + l3 + l4)
print()
print("A area é: ",area)
print("O perimetro é: ",perimetro)